In [3]:
import numpy as np

In [6]:
#(1,2) (строкии, столбцы)

In [53]:
a = np.array([1,2,3,4])
print(a.dtype)

print(a[1])

a[1] = 999
print(a[1])

print(a[ [1,2,0] ])


a = a.reshape(2,2)

print(a)

a[0][0]


int64
2
999
[999   3   1]
[[  1 999]
 [  3   4]]


1

In [86]:
b = np.array([x for x in range(10)], 'float64')

In [87]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [48]:
c = np.array([[1,2],[3,4],[5,6]])
c[0,1]

2

In [93]:
 np.empty((5, 5))

array([[2.68156159e+154, 2.68156159e+154, 6.91691904e-323,
        0.00000000e+000, 0.00000000e+000],
       [2.23088143e+180, 9.85655925e+165, 4.25716249e+174,
        4.08289618e+179, 8.98351204e-067],
       [1.14284006e-071, 1.46420293e-075, 7.34491277e-043,
        0.00000000e+000, 2.68156159e+154],
       [2.68156159e+154, 2.68156159e+154, 2.68156159e+154,
        2.96439388e-323, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 2.68156159e+154,
        2.68156159e+154, 1.48219694e-323]])

In [79]:
np.zeros([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [83]:
np.ones([4,3], dtype='int8')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [84]:
np.full([3,2], -1)

array([[-1, -1],
       [-1, -1],
       [-1, -1]])

In [90]:
np.mat('1 2 3 4')

matrix([[1, 2, 3, 4]])

In [91]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [96]:
a = np.mat([(1,2,3), (11,22,33), (111,222,333)])
a

matrix([[  1,   2,   3],
        [ 11,  22,  33],
        [111, 222, 333]])

In [97]:
np.tril(a)

array([[  1,   0,   0],
       [ 11,  22,   0],
       [111, 222, 333]])

In [98]:
np.triu(a)

array([[  1,   2,   3],
       [  0,  22,  33],
       [  0,   0, 333]])

In [100]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [101]:
np.arange(1,5)

array([1, 2, 3, 4])

In [104]:
np.arange(0, 5, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [109]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [106]:
a.dtype

dtype('int64')

In [107]:
a.size

4

In [116]:
a.shape = 2,2

In [117]:
a

array([[1, 2],
       [3, 4]])

In [120]:
a1 = np.arange(1,5)
a1

array([1, 2, 3, 4])

In [132]:
a1.reshape(2, 2, 1) # - 2 масима и в каждом еще 2 масима в которых по 1 елементу 

array([[[1],
        [2]],

       [[3],
        [4]]])

In [147]:
a = np.array([1,2,3,4,5,6,7,8,9])
b =  a # b ссылается на тот же масим что и а, про изменении ю поменяется и а 

a.shape = 3, 3, 1
b

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [142]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a.view() # b копия представления данных

a.shape = 3, 3

b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
a = np.array([1,2,3,4,5,6,7,8,9])

b = np.array(a) # b копия представления данных
b = np.copy(a) # b копия представления данных


a.shape = 3, 3 

b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [221]:
a = np.array([1,2,3])


In [215]:
mean = sum(a) / len(a)
mean

2.0

In [222]:

def dot(v,w) :
    """Computes v_1 * w_1 + ... + v_n * w_n"""
    assert len(v) == len(w), "vectors must be same length"

    print([v_i * w_i for v_i, w_i in zip(v, w)])
    return sum(v_i * w_i for v_i, w_i in zip(v, w))


def sum_of_squares(v):
    """Returns v_1 * v_1 + ... + v_n * v_n"""

    return dot(v, v)





In [223]:
sum_of_squares([x - mean for x in a ])

[1.0, 0.0, 1.0]


2.0